# Generated by Django 4.2 on 2025-01-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="role",
            field=models.CharField(default="admin", max_length=10),
        ),
        migrations.AddField(
            model_name="doctor",
            name="role",
            field=models.CharField(default="doctor", max_length=10),
        ),
        migrations.AddField(
            model_name="patient",
            name="role",
            field=models.CharField(default="patient", max_length=10),
        ),
    ]
