# Generated by Django 4.2 on 2025-01-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("management", "0002_admin_role_doctor_role_patient_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="role",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="role",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="role",
        ),
        migrations.AddField(
            model_name="admin",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="patient_set",
                related_query_name="patient",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
    ]
