# Generated by Django 4.2 on 2025-01-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_remove_admin_role_remove_doctor_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
